### ISSUE TITLE
大佬可有jdgs算法

### ISSUE THREAD

**Issue by newpurr** [ppwang06/frida_js#1]

**Comment by ppwang06** [comment]
你要抓哪个接口， 详情页jdgs这个参数还没参与校验

**Comment by newpurr** [comment]
高版本的商品详情需要验证jdgs参数了

**Comment by newpurr** [comment]
https://api.m.jd.com/client.action?wareBusiness 最新版本

**Comment by ppwang06** [comment]
我试了 12.0.4的 没有验证

**Comment by ppwang06** [comment]
你哪个版本的

**Comment by ppwang06** [comment]
这个需要进so层  我只看Java层  so层还没看

**Comment by newpurr** [comment]
11.8.4

**Comment by newpurr** [comment]
我试了不加这个头我访问就会失败

**Comment by newpurr** [comment]
本来试着看下so层的，看不懂，无从下手

**Comment by ppwang06** [comment]
等我看下这个版本的app

**Comment by newpurr** [comment]
麻烦大佬啦

**Comment by ppwang06** [comment]
我试了下 jdgs不需要 需要cookie有unionwsws 这个参数 我用的也是11.8.4的版本 你讲jdgs提供值为""试过吗？我之前忘了哪个版本的确实需要jdgs 后面又不需要了

**Comment by newpurr** [comment]
我将值设置为null可以
<img width="896" alt="image" src="https://github.com/ppwang06/frida_js/assets/19930163/2b3cda12-f255-4370-a9d9-b6ffd5284382">

**Comment by newpurr** [comment]
ck里面包含unionwsws，不过好像我的脚本又出幺蛾子了，开始出现: {"code":"600","echo":"signature verification failed"}

**Comment by ppwang06** [comment]
600不是你的 sign签名不太对

**Comment by ppwang06** [comment]
{"code":"600","echo":"signature verification failed"}  是参数sign没算对  你用什么语言写的

**Comment by newpurr** [comment]
好像除了详情都行，地址预约这些都没问题

**Comment by newpurr** [comment]
go

**Comment by ppwang06** [comment]
你登陆后抓的？ 详情还是抓不到吗

**Comment by newpurr** [comment]
我重新获取ck再试试

**Comment by newpurr** [comment]
应该是我将base64翻译成go版本的代码有问题，里面有转义字符的时候就会导致base64 encode出来的数据错误

**Comment by ppwang06** [comment]
body加密的类base64那个加密吗

**Comment by newpurr** [comment]
对头，只要有中文就会出问题，是说不得断断续续出现

**Comment by newpurr** [comment]
非常感谢大佬，又解决一个问题

**Comment by ppwang06** [comment]
中文的那个加密  Python的也会出问题 我升级过一版  [body加密](https://github.com/ppwang06/frida_js/blob/main/apps/jingdong/get_base_str.py) 你可以按照用ChatGPT着翻一下go版本的 如果 还不行 这两天 我写个go版本的 你看下

**Comment by ppwang06** [comment]
go版本的 你比对下  [go版本body加密](https://github.com/ppwang06/frida_js/blob/main/apps/jingdong/get_base_str.go)  我之前写的第一版包含中文加密会有问题

**Comment by ppwang06** [comment]
@newpurr 看下上面我的回复，中文的问题我后面修复了 你可能没看到  [看下最新代码](https://github.com/ppwang06/frida_js/blob/main/apps/jingdong/get_base_str.go)

**Comment by newpurr** [comment]
golang 实现魔改base64只需要 `base64.NewEncoding(base64List).EncodeToString([]byte(input))` 更换码表即可，不用自己写算法 @ppwang06

**Comment by ppwang06** [comment]
好的 已经合了

**Comment by Destinychen5** [comment]
两位大佬，12.0.8版本调用currentOrder接口，偶尔提示活动火爆，是和jdgs有关吗？

**Comment by Linkangyis** [comment]
12.0.0_搜索已经开启校验了

**Comment by jiefengH** [comment]
JAVA新手，还不懂这个jdgs怎么用unidbgg还原。
